### ISSUE TITLE
Detect is unnecessarily noisy when pyproject.toml file does not exist

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/poetry#27]
Detect should fail silently when `pyproject.toml` is not present. It should only display an error to the user when the file exists and there is an issue with it.

Example output of running detect against a non-poetry app:
```
======== Output: paketo-buildpacks/poetry@0.1.2 ========
pyproject.toml must include [tool.poetry.dependencies.python], see https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies
err:  paketo-buildpacks/poetry@0.1.2 
```

Proposal:

* We should probably return an empty string and nil error from:
https://github.com/paketo-buildpacks/poetry/blob/4583111bf857b79ec07ef9fa77fa93538b680d4f/pyproject_parser.go#L30
* In `detect.go` we should return `packit.Fail` if there is no error and an empty string.

**Comment by thitch97** [comment]
@robdimsdale why would we need to return `packit.Fail` if there's no error and an empty string?

**Comment by robdimsdale** [comment]
My thinking is that we should not pass detect if there is no `pyproject.toml` file - it is a valid use-case for a non-poetry app. My understanding is that this is exactly the use-case the `packit.Fail` sentinel error value is designed to capture.
